server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
                    - id: userManager_users
                      uri: http://localhost:8090
                      predicates:
                        - Path=/users/**

                    - id: userManager_auth
                      uri: http://localhost:8090
                      predicates:
                        - Path=/auth/**